---
repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.19.0"
    hooks:
      - id: terraform-docs-go
        args:
          - "-c"
          - ".terraform-docs.yml"
          - "--output-file"
          - "README.md"
          - "./"
        always_run: true
      - id: terraform-docs-go
        args:
          - "-c"
          - "./examples/.terraform-docs.yml"
          - "--output-file"
          - "README.md"
          - "./examples/default"
        always_run: true