---
name: $(year:yyyy).$(Month).$(DayOfMonth)$(rev:.r)

trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: git
      name: WKEnterprise
      ref: main

variables:
  - template: templates/yaml/variables/common-module-variables.yml@templates

stages:
  - template: templates/yaml/stages/tf-module-ci.yml@templates
